#!/bin/bash
pastmode=`cat /sys/devices/platform/thinkpad_acpi/hotkey_tablet_mode`
while [ true ]
do
  nowmode=`cat /sys/devices/platform/thinkpad_acpi/hotkey_tablet_mode`
  if test 1 = $pastmode
  then  
    if test 0 = $nowmode
    then
      echo 3 > ~/rotatescripts/rotationmode
      ~/rotatescripts/rotatebutton
      pastmode=0
    fi
  fi
  if test 0 = $pastmode
  then
    if test 1 = $nowmode
    then
      echo 1 > ~/rotatescripts/rotationmode #1 for inverted, 2 for right, 0 for left
      ~/rotatescripts/rotatebutton
      pastmode=1
    fi
  fi
  sleep 2
done
